/**
 * GENERATED by `scripts/gen-export-palette.mjs` from `app/globals.css`.
 * Do not edit: run `pnpm gen:export-palette`. `pnpm check:export-palette`
 * fails when this file and the CSS disagree.
 *
 * Every theme's export palette as concrete sRGB, for the callers that have no
 * document to compute styles from — the render route draws a diagram on the
 * server, where `resolveExportTheme()` cannot run. On screen that function is
 * still the only right answer, because it reads the palette the reader is
 * actually looking at; this table is what the server has instead.
 */

import type { Theme } from "@/lib/constants";

import type { ExportTheme } from "./theme";

/** Every theme in `THEMES`, resolved. */
export const EXPORT_PALETTES: Record<Theme, ExportTheme> = {
  "light": {
    "canvas": "#f6f7f9",
    "node": "#ffffff",
    "nodeForeground": "#141822",
    "nodeBorder": "#83868e",
    "edge": "#7a808d",
    "primary": "#6963ec",
    "accent": "#00bfc0",
    "destructive": "#df2225",
    "destructiveForeground": "#fff8f6",
    "mutedForeground": "#666c78",
    "foreground": "#141822",
    "edgeDrift": "#6675c8",
    "criticalCap": "#6963ec",
    "nodeMeta": "#4e5564",
    "canvasGrid": "#d5d7dd",
    "nodeRoles": {
      "person": {
        "fill": "#e9e4fe",
        "border": "#7553bd"
      },
      "internal": {
        "fill": "#d7eafe",
        "border": "#1f6cb0"
      },
      "external": {
        "fill": "#eff0f3",
        "border": "#83868e"
      },
      "database": {
        "fill": "#bef4f3",
        "border": "#067272"
      },
      "queue": {
        "fill": "#d0f5d7",
        "border": "#317a45"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#d0f5d7",
        "border": "#317a45"
      },
      "end": {
        "fill": "#fddeee",
        "border": "#a5417f"
      },
      "step": {
        "fill": "#d7eafe",
        "border": "#1f6cb0"
      },
      "decision": {
        "fill": "#fae6bb",
        "border": "#85621d"
      },
      "io": {
        "fill": "#bef4f3",
        "border": "#067272"
      },
      "call": {
        "fill": "#e9e4fe",
        "border": "#7553bd"
      }
    },
    "roleTexture": {
      "ink": "#83868e",
      "opacity": 0
    }
  },
  "paper": {
    "canvas": "#fdfbf5",
    "node": "#fbf7ef",
    "nodeForeground": "#2c221a",
    "nodeBorder": "#7a7064",
    "edge": "#6e6054",
    "primary": "#a63c0c",
    "accent": "#00bfc0",
    "destructive": "#df2225",
    "destructiveForeground": "#fff8f6",
    "mutedForeground": "#685f54",
    "foreground": "#2a1d15",
    "edgeDrift": "#905029",
    "criticalCap": "#a63c0c",
    "nodeMeta": "#5d5348",
    "canvasGrid": "#e2dcd1",
    "nodeRoles": {
      "person": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#7553bd"
      },
      "internal": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#1f6cb0"
      },
      "external": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#7a7064"
      },
      "database": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#067272"
      },
      "queue": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#317a45"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#317a45"
      },
      "end": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#a5417f"
      },
      "step": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#1f6cb0"
      },
      "decision": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#85621d"
      },
      "io": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#067272"
      },
      "call": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#7553bd"
      }
    },
    "roleTexture": {
      "ink": "#7a7064",
      "opacity": 0
    }
  },
  "pastel": {
    "canvas": "#d2d3e1",
    "node": "#e0e0ec",
    "nodeForeground": "#262635",
    "nodeBorder": "#7f7f8a",
    "edge": "#797d8a",
    "primary": "#5a66b9",
    "accent": "#eaa0aa",
    "destructive": "#bd4049",
    "destructiveForeground": "#f2e4e4",
    "mutedForeground": "#565666",
    "foreground": "#262635",
    "edgeDrift": "#6670a7",
    "criticalCap": "#4f5aac",
    "nodeMeta": "#4b4b5c",
    "canvasGrid": "#c3c3d9",
    "nodeRoles": {
      "person": {
        "fill": "#d4c9ec",
        "border": "#7457a3"
      },
      "internal": {
        "fill": "#bfd0f1",
        "border": "#3e68ad"
      },
      "external": {
        "fill": "#d2d3e3",
        "border": "#686872"
      },
      "database": {
        "fill": "#afd6ea",
        "border": "#116d8a"
      },
      "queue": {
        "fill": "#addcd5",
        "border": "#007459"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#addcd5",
        "border": "#007459"
      },
      "end": {
        "fill": "#f0c4c9",
        "border": "#a94753"
      },
      "step": {
        "fill": "#bfd0f1",
        "border": "#3e68ad"
      },
      "decision": {
        "fill": "#deceab",
        "border": "#876114"
      },
      "io": {
        "fill": "#afd6ea",
        "border": "#116d8a"
      },
      "call": {
        "fill": "#d4c9ec",
        "border": "#7457a3"
      }
    },
    "roleTexture": {
      "ink": "#7f7f8a",
      "opacity": 0
    }
  },
  "glass": {
    "canvas": "#e7edf6",
    "node": "rgba(255, 255, 255, 0.62)",
    "nodeForeground": "#141822",
    "nodeBorder": "#83868e",
    "edge": "#7a808d",
    "primary": "#6963ec",
    "accent": "#00bfc0",
    "destructive": "#df2225",
    "destructiveForeground": "#fff8f6",
    "mutedForeground": "#666c78",
    "foreground": "#141822",
    "edgeDrift": "#6675c8",
    "criticalCap": "#6963ec",
    "nodeMeta": "#4e5564",
    "canvasGrid": "#cdd5df",
    "nodeRoles": {
      "person": {
        "fill": "#e9e4fe",
        "border": "#7553bd"
      },
      "internal": {
        "fill": "#d7eafe",
        "border": "#1f6cb0"
      },
      "external": {
        "fill": "rgba(239, 242, 247, 0.6)",
        "border": "#83868e"
      },
      "database": {
        "fill": "#bef4f3",
        "border": "#067272"
      },
      "queue": {
        "fill": "#d0f5d7",
        "border": "#317a45"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#d0f5d7",
        "border": "#317a45"
      },
      "end": {
        "fill": "#fddeee",
        "border": "#a5417f"
      },
      "step": {
        "fill": "#d7eafe",
        "border": "#1f6cb0"
      },
      "decision": {
        "fill": "#fae6bb",
        "border": "#85621d"
      },
      "io": {
        "fill": "#bef4f3",
        "border": "#067272"
      },
      "call": {
        "fill": "#e9e4fe",
        "border": "#7553bd"
      }
    },
    "roleTexture": {
      "ink": "#83868e",
      "opacity": 0
    }
  },
  "dark": {
    "canvas": "#12141a",
    "node": "#181a20",
    "nodeForeground": "#f0f2f5",
    "nodeBorder": "#757983",
    "edge": "#8b8d95",
    "primary": "#8f81ff",
    "accent": "#1ad1d1",
    "destructive": "#f4514f",
    "destructiveForeground": "#180807",
    "mutedForeground": "#a2a4ac",
    "foreground": "#f0f2f5",
    "edgeDrift": "#858bdb",
    "criticalCap": "#8f81ff",
    "nodeMeta": "#b7bac2",
    "canvasGrid": "#282a30",
    "nodeRoles": {
      "person": {
        "fill": "#3a2e58",
        "border": "#a489ed"
      },
      "internal": {
        "fill": "#1a3754",
        "border": "#599fe4"
      },
      "external": {
        "fill": "#1d1f25",
        "border": "#757983"
      },
      "database": {
        "fill": "#003d3d",
        "border": "#01acad"
      },
      "queue": {
        "fill": "#1d3e25",
        "border": "#61ae73"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#1d3e25",
        "border": "#61ae73"
      },
      "end": {
        "fill": "#4a293c",
        "border": "#d778b0"
      },
      "step": {
        "fill": "#1a3754",
        "border": "#599fe4"
      },
      "decision": {
        "fill": "#43330c",
        "border": "#c29440"
      },
      "io": {
        "fill": "#003d3d",
        "border": "#01acad"
      },
      "call": {
        "fill": "#3a2e58",
        "border": "#a489ed"
      }
    },
    "roleTexture": {
      "ink": "#757983",
      "opacity": 0
    }
  },
  "midnight": {
    "canvas": "#000000",
    "node": "#10121b",
    "nodeForeground": "#f0f1f6",
    "nodeBorder": "#676b7a",
    "edge": "#828593",
    "primary": "#8f81ff",
    "accent": "#1ad1d1",
    "destructive": "#f4514f",
    "destructiveForeground": "#180807",
    "mutedForeground": "#a1a4b0",
    "foreground": "#f0f1f6",
    "edgeDrift": "#8487da",
    "criticalCap": "#8f81ff",
    "nodeMeta": "#b6bac8",
    "canvasGrid": "#14161d",
    "nodeRoles": {
      "person": {
        "fill": "#2c2047",
        "border": "#9f85e5"
      },
      "internal": {
        "fill": "#0d2944",
        "border": "#579adc"
      },
      "external": {
        "fill": "#14171d",
        "border": "#676b7a"
      },
      "database": {
        "fill": "#002e2f",
        "border": "#12a7a7"
      },
      "queue": {
        "fill": "#112f19",
        "border": "#60a871"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#112f19",
        "border": "#60a871"
      },
      "end": {
        "fill": "#3a1c2e",
        "border": "#d075ab"
      },
      "step": {
        "fill": "#0d2944",
        "border": "#579adc"
      },
      "decision": {
        "fill": "#342501",
        "border": "#bc9041"
      },
      "io": {
        "fill": "#002e2f",
        "border": "#12a7a7"
      },
      "call": {
        "fill": "#2c2047",
        "border": "#9f85e5"
      }
    },
    "roleTexture": {
      "ink": "#676b7a",
      "opacity": 0
    }
  },
  "contrast": {
    "canvas": "#000000",
    "node": "#070707",
    "nodeForeground": "#ffffff",
    "nodeBorder": "#cdd0df",
    "edge": "#babdcb",
    "primary": "#baafff",
    "accent": "#53f2f2",
    "destructive": "#ff706a",
    "destructiveForeground": "#180807",
    "mutedForeground": "#d7d7d7",
    "foreground": "#ffffff",
    "edgeDrift": "#b3b8ff",
    "criticalCap": "#baafff",
    "nodeMeta": "#dcdee5",
    "canvasGrid": "#2e2e2e",
    "nodeRoles": {
      "person": {
        "fill": "#190f2e",
        "border": "#d4bbff"
      },
      "internal": {
        "fill": "#03172c",
        "border": "#90d4ff"
      },
      "external": {
        "fill": "#090b0f",
        "border": "#cdd0df"
      },
      "database": {
        "fill": "#001c1d",
        "border": "#70ebeb"
      },
      "queue": {
        "fill": "#021c09",
        "border": "#9fe9ae"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#021c09",
        "border": "#9fe9ae"
      },
      "end": {
        "fill": "#250b1b",
        "border": "#f9b6db"
      },
      "step": {
        "fill": "#03172c",
        "border": "#90d4ff"
      },
      "decision": {
        "fill": "#1f1400",
        "border": "#facc7e"
      },
      "io": {
        "fill": "#001c1d",
        "border": "#70ebeb"
      },
      "call": {
        "fill": "#190f2e",
        "border": "#d4bbff"
      }
    },
    "roleTexture": {
      "ink": "#cdd0df",
      "opacity": 0
    }
  },
  "blueprint": {
    "canvas": "#011d37",
    "node": "#04213c",
    "nodeForeground": "#eff6fd",
    "nodeBorder": "#6c839b",
    "edge": "#7e95ad",
    "primary": "#9c92ff",
    "accent": "#4ddcdc",
    "destructive": "#fc5855",
    "destructiveForeground": "#180807",
    "mutedForeground": "#a9b9ca",
    "foreground": "#eff6fd",
    "edgeDrift": "#8298e8",
    "criticalCap": "#9c92ff",
    "nodeMeta": "#b2bfce",
    "canvasGrid": "#324f6e",
    "nodeRoles": {
      "person": {
        "fill": "#3c305c",
        "border": "#a98cf4"
      },
      "internal": {
        "fill": "#1b3a58",
        "border": "#5aa3ec"
      },
      "external": {
        "fill": "#06243f",
        "border": "#6c839b"
      },
      "database": {
        "fill": "#004040",
        "border": "#00b2b2"
      },
      "queue": {
        "fill": "#1f4127",
        "border": "#63b376"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#1f4127",
        "border": "#63b376"
      },
      "end": {
        "fill": "#4e2b3f",
        "border": "#de7bb5"
      },
      "step": {
        "fill": "#1b3a58",
        "border": "#5aa3ec"
      },
      "decision": {
        "fill": "#46350d",
        "border": "#c9983f"
      },
      "io": {
        "fill": "#004040",
        "border": "#00b2b2"
      },
      "call": {
        "fill": "#3c305c",
        "border": "#a98cf4"
      }
    },
    "roleTexture": {
      "ink": "#6c839b",
      "opacity": 0
    }
  },
  "eink": {
    "canvas": "#ededed",
    "node": "#fafafa",
    "nodeForeground": "#161616",
    "nodeBorder": "#808080",
    "edge": "#696969",
    "primary": "#4d4d4d",
    "accent": "#717171",
    "destructive": "#424242",
    "destructiveForeground": "#fafafa",
    "mutedForeground": "#585858",
    "foreground": "#161616",
    "edgeDrift": "#585858",
    "criticalCap": "#4d4d4d",
    "nodeMeta": "#3c3c3c",
    "canvasGrid": "#d1d1d1",
    "nodeRoles": {
      "person": {
        "fill": "#dfdfdf",
        "border": "#636363"
      },
      "internal": {
        "fill": "#d7d7d7",
        "border": "#525252"
      },
      "external": {
        "fill": "#f0f0f0",
        "border": "#868686"
      },
      "database": {
        "fill": "#cfcfcf",
        "border": "#424242"
      },
      "queue": {
        "fill": "#e8e8e8",
        "border": "#747474"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#e8e8e8",
        "border": "#747474"
      },
      "end": {
        "fill": "#bfbfbf",
        "border": "#242424"
      },
      "step": {
        "fill": "#d7d7d7",
        "border": "#525252"
      },
      "decision": {
        "fill": "#c7c7c7",
        "border": "#333333"
      },
      "io": {
        "fill": "#cfcfcf",
        "border": "#424242"
      },
      "call": {
        "fill": "#dfdfdf",
        "border": "#636363"
      }
    },
    "roleTexture": {
      "ink": "#4d4d4d",
      "opacity": 0.14
    }
  }
} as const;

/**
 * One theme's palette, for a caller holding a name it has already validated
 * against `THEMES`. Unknown names cannot be constructed through `Theme`, so
 * there is no fallback here to disagree with the route's own default.
 */
export function exportPaletteFor(theme: Theme): ExportTheme {
  return EXPORT_PALETTES[theme];
}
