/**
 * GENERATED by `scripts/gen-export-palette.mjs` from `app/globals.css`.
 * Do not edit: run `pnpm gen:export-palette`. `pnpm check:export-palette`
 * fails when this file and the CSS disagree.
 *
 * Every theme's export palette as concrete sRGB, for the callers that have no
 * document to compute styles from — the render route draws a diagram on the
 * server, where `resolveExportTheme()` cannot run. On screen that function is
 * still the only right answer, because it reads the palette the reader is
 * actually looking at; this table is what the server has instead.
 */

import type { Theme } from "@/lib/constants";

import type { ExportTheme } from "./theme";

/** Every theme in `THEMES`, resolved. */
export const EXPORT_PALETTES: Record<Theme, ExportTheme> = {
  "light": {
    "canvas": "#f6f7f9",
    "node": "#ffffff",
    "nodeForeground": "#141822",
    "nodeBorder": "#83868e",
    "edge": "#7a808d",
    "primary": "#6963ec",
    "accent": "#00bfc0",
    "destructive": "#df2225",
    "destructiveForeground": "#fff8f6",
    "mutedForeground": "#666c78",
    "foreground": "#141822",
    "secondary": "#eef0f4",
    "secondaryForeground": "#242933",
    "border": "#dbdee3",
    "edgeDrift": "#6675c8",
    "criticalCap": "#6963ec",
    "nodeMeta": "#4e5564",
    "canvasGrid": "#d5d7dd",
    "nodeRoles": {
      "person": {
        "fill": "#e9e4fe",
        "border": "#7553bd"
      },
      "internal": {
        "fill": "#d7eafe",
        "border": "#1f6cb0"
      },
      "external": {
        "fill": "#eff0f3",
        "border": "#83868e"
      },
      "database": {
        "fill": "#bef4f3",
        "border": "#067272"
      },
      "queue": {
        "fill": "#d0f5d7",
        "border": "#317a45"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#d0f5d7",
        "border": "#317a45"
      },
      "end": {
        "fill": "#fddeee",
        "border": "#a5417f"
      },
      "step": {
        "fill": "#d7eafe",
        "border": "#1f6cb0"
      },
      "decision": {
        "fill": "#fae6bb",
        "border": "#85621d"
      },
      "io": {
        "fill": "#bef4f3",
        "border": "#067272"
      },
      "call": {
        "fill": "#e9e4fe",
        "border": "#7553bd"
      }
    },
    "tagFill": {
      "lightness": 0.93,
      "chromaCap": 0.055
    },
    "seq": {
      "lanes": [
        {
          "lane": "#1baf7a",
          "cardFill": "#c8f4dd",
          "cardTop": "#caf5e7",
          "cardBottom": "#b7ecd1",
          "line": "#409aa7"
        },
        {
          "lane": "#eb6834",
          "cardFill": "#ffdccc",
          "cardTop": "#ffded9",
          "cardBottom": "#fecfba",
          "line": "#b672a0"
        },
        {
          "lane": "#2a78d6",
          "cardFill": "#d0eaff",
          "cardTop": "#d5ecff",
          "cardBottom": "#bbddfa",
          "line": "#597db6"
        },
        {
          "lane": "#e87ba4",
          "cardFill": "#ffd9e8",
          "cardTop": "#fbddf0",
          "cardBottom": "#fdcee0",
          "line": "#a883b8"
        },
        {
          "lane": "#4a3aa7",
          "cardFill": "#e2e4ff",
          "cardTop": "#e3e7ff",
          "cardBottom": "#cdd0f5",
          "line": "#55609f"
        }
      ],
      "noteFill": "#fcf0e1",
      "noteStroke": "#e2bc8a"
    },
    "roleTexture": {
      "ink": "#83868e",
      "opacity": 0
    }
  },
  "paper": {
    "canvas": "#fdfbf5",
    "node": "#fbf7ef",
    "nodeForeground": "#2c221a",
    "nodeBorder": "#7a7064",
    "edge": "#6e6054",
    "primary": "#a63c0c",
    "accent": "#00bfc0",
    "destructive": "#df2225",
    "destructiveForeground": "#fff8f6",
    "mutedForeground": "#685f54",
    "foreground": "#2a1d15",
    "secondary": "#f1ede5",
    "secondaryForeground": "#30271f",
    "border": "#d2cbc1",
    "edgeDrift": "#905029",
    "criticalCap": "#a63c0c",
    "nodeMeta": "#5d5348",
    "canvasGrid": "#e2dcd1",
    "nodeRoles": {
      "person": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#7553bd"
      },
      "internal": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#1f6cb0"
      },
      "external": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#7a7064"
      },
      "database": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#067272"
      },
      "queue": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#317a45"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#317a45"
      },
      "end": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#a5417f"
      },
      "step": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#1f6cb0"
      },
      "decision": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#85621d"
      },
      "io": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#067272"
      },
      "call": {
        "fill": "rgba(0, 0, 0, 0)",
        "border": "#7553bd"
      }
    },
    "tagFill": {
      "lightness": 0.942,
      "chromaCap": 0.055
    },
    "seq": {
      "lanes": [
        {
          "lane": "#1baf7a",
          "cardFill": "#ccf8e1",
          "cardTop": "#d5f7de",
          "cardBottom": "#bbefd4",
          "line": "#798646"
        },
        {
          "lane": "#eb6834",
          "cardFill": "#ffe0d0",
          "cardTop": "#fee3d2",
          "cardBottom": "#fed3bd",
          "line": "#b16a3e"
        },
        {
          "lane": "#2a78d6",
          "cardFill": "#d4eeff",
          "cardTop": "#d4f1fa",
          "cardBottom": "#bde1fa",
          "line": "#915889"
        },
        {
          "lane": "#e87ba4",
          "cardFill": "#ffddec",
          "cardTop": "#ffdfe8",
          "cardBottom": "#fdd1e4",
          "line": "#b67168"
        },
        {
          "lane": "#4a3aa7",
          "cardFill": "#e6e8ff",
          "cardTop": "#efe7fc",
          "cardBottom": "#d1d3f5",
          "line": "#813e64"
        }
      ],
      "noteFill": "#fbedd9",
      "noteStroke": "#ddb479"
    },
    "roleTexture": {
      "ink": "#7a7064",
      "opacity": 0
    }
  },
  "pastel": {
    "canvas": "#d2d3e1",
    "node": "#e0e0ec",
    "nodeForeground": "#262635",
    "nodeBorder": "#7f7f8a",
    "edge": "#797d8a",
    "primary": "#5a66b9",
    "accent": "#eaa0aa",
    "destructive": "#bd4049",
    "destructiveForeground": "#f2e4e4",
    "mutedForeground": "#565666",
    "foreground": "#262635",
    "secondary": "#cdcde0",
    "secondaryForeground": "#2b2b39",
    "border": "#c2c2d5",
    "edgeDrift": "#6670a7",
    "criticalCap": "#4f5aac",
    "nodeMeta": "#4b4b5c",
    "canvasGrid": "#c3c3d9",
    "nodeRoles": {
      "person": {
        "fill": "#d4c9ec",
        "border": "#7457a3"
      },
      "internal": {
        "fill": "#bfd0f1",
        "border": "#3e68ad"
      },
      "external": {
        "fill": "#d2d3e3",
        "border": "#686872"
      },
      "database": {
        "fill": "#afd6ea",
        "border": "#116d8a"
      },
      "queue": {
        "fill": "#addcd5",
        "border": "#007459"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#addcd5",
        "border": "#007459"
      },
      "end": {
        "fill": "#f0c4c9",
        "border": "#a94753"
      },
      "step": {
        "fill": "#bfd0f1",
        "border": "#3e68ad"
      },
      "decision": {
        "fill": "#deceab",
        "border": "#876114"
      },
      "io": {
        "fill": "#afd6ea",
        "border": "#116d8a"
      },
      "call": {
        "fill": "#d4c9ec",
        "border": "#7457a3"
      }
    },
    "tagFill": {
      "lightness": 0.93,
      "chromaCap": 0.055
    },
    "seq": {
      "lanes": [
        {
          "lane": "#1baf7a",
          "cardFill": "#c8f4dd",
          "cardTop": "#c3f2e5",
          "cardBottom": "#b7ecd1",
          "line": "#4198a9"
        },
        {
          "lane": "#eb6834",
          "cardFill": "#ffdccc",
          "cardTop": "#fedad2",
          "cardBottom": "#fecfba",
          "line": "#b7709a"
        },
        {
          "lane": "#2a78d6",
          "cardFill": "#d0eaff",
          "cardTop": "#d2e7fd",
          "cardBottom": "#bbddfa",
          "line": "#5d7ab5"
        },
        {
          "lane": "#e87ba4",
          "cardFill": "#ffd9e8",
          "cardTop": "#fad9eb",
          "cardBottom": "#fdcee0",
          "line": "#aa81b3"
        },
        {
          "lane": "#4a3aa7",
          "cardFill": "#e2e4ff",
          "cardTop": "#e1e2fc",
          "cardBottom": "#cdd0f5",
          "line": "#595d9d"
        }
      ],
      "noteFill": "#dfd5d2",
      "noteStroke": "#d4b189"
    },
    "roleTexture": {
      "ink": "#7f7f8a",
      "opacity": 0
    }
  },
  "glass": {
    "canvas": "#e7edf6",
    "node": "rgba(255, 255, 255, 0.62)",
    "nodeForeground": "#141822",
    "nodeBorder": "#83868e",
    "edge": "#7a808d",
    "primary": "#6963ec",
    "accent": "#00bfc0",
    "destructive": "#df2225",
    "destructiveForeground": "#fff8f6",
    "mutedForeground": "#666c78",
    "foreground": "#141822",
    "secondary": "rgba(227, 232, 240, 0.6)",
    "secondaryForeground": "#242933",
    "border": "rgba(128, 134, 147, 0.28)",
    "edgeDrift": "#6675c8",
    "criticalCap": "#6963ec",
    "nodeMeta": "#4e5564",
    "canvasGrid": "#cdd5df",
    "nodeRoles": {
      "person": {
        "fill": "#e9e4fe",
        "border": "#7553bd"
      },
      "internal": {
        "fill": "#d7eafe",
        "border": "#1f6cb0"
      },
      "external": {
        "fill": "rgba(239, 242, 247, 0.6)",
        "border": "#83868e"
      },
      "database": {
        "fill": "#bef4f3",
        "border": "#067272"
      },
      "queue": {
        "fill": "#d0f5d7",
        "border": "#317a45"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#d0f5d7",
        "border": "#317a45"
      },
      "end": {
        "fill": "#fddeee",
        "border": "#a5417f"
      },
      "step": {
        "fill": "#d7eafe",
        "border": "#1f6cb0"
      },
      "decision": {
        "fill": "#fae6bb",
        "border": "#85621d"
      },
      "io": {
        "fill": "#bef4f3",
        "border": "#067272"
      },
      "call": {
        "fill": "#e9e4fe",
        "border": "#7553bd"
      }
    },
    "tagFill": {
      "lightness": 0.93,
      "chromaCap": 0.055
    },
    "seq": {
      "lanes": [
        {
          "lane": "#1baf7a",
          "cardFill": "#c8f4dd",
          "cardTop": "#c8f4e6",
          "cardBottom": "#b7ecd1",
          "line": "#409aa7"
        },
        {
          "lane": "#eb6834",
          "cardFill": "#ffdccc",
          "cardTop": "#ffdcd7",
          "cardBottom": "#fecfba",
          "line": "#b672a0"
        },
        {
          "lane": "#2a78d6",
          "cardFill": "#d0eaff",
          "cardTop": "#d4ebfe",
          "cardBottom": "#bbddfa",
          "line": "#597db6"
        },
        {
          "lane": "#e87ba4",
          "cardFill": "#ffd9e8",
          "cardTop": "#fbdcef",
          "cardBottom": "#fdcee0",
          "line": "#a883b8"
        },
        {
          "lane": "#4a3aa7",
          "cardFill": "#e2e4ff",
          "cardTop": "#e2e6ff",
          "cardBottom": "#cdd0f5",
          "line": "#55609f"
        }
      ],
      "noteFill": "rgba(252, 240, 225, 0.622)",
      "noteStroke": "rgba(184, 149, 104, 0.676)"
    },
    "roleTexture": {
      "ink": "#83868e",
      "opacity": 0
    }
  },
  "dark": {
    "canvas": "#12141a",
    "node": "#181a20",
    "nodeForeground": "#f0f2f5",
    "nodeBorder": "#757983",
    "edge": "#8b8d95",
    "primary": "#8f81ff",
    "accent": "#1ad1d1",
    "destructive": "#f4514f",
    "destructiveForeground": "#180807",
    "mutedForeground": "#a2a4ac",
    "foreground": "#f0f2f5",
    "secondary": "#34363d",
    "secondaryForeground": "#eaebef",
    "border": "#3f4147",
    "edgeDrift": "#858bdb",
    "criticalCap": "#8f81ff",
    "nodeMeta": "#b7bac2",
    "canvasGrid": "#282a30",
    "nodeRoles": {
      "person": {
        "fill": "#3a2e58",
        "border": "#a489ed"
      },
      "internal": {
        "fill": "#1a3754",
        "border": "#599fe4"
      },
      "external": {
        "fill": "#1d1f25",
        "border": "#757983"
      },
      "database": {
        "fill": "#003d3d",
        "border": "#01acad"
      },
      "queue": {
        "fill": "#1d3e25",
        "border": "#61ae73"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#1d3e25",
        "border": "#61ae73"
      },
      "end": {
        "fill": "#4a293c",
        "border": "#d778b0"
      },
      "step": {
        "fill": "#1a3754",
        "border": "#599fe4"
      },
      "decision": {
        "fill": "#43330c",
        "border": "#c29440"
      },
      "io": {
        "fill": "#003d3d",
        "border": "#01acad"
      },
      "call": {
        "fill": "#3a2e58",
        "border": "#a489ed"
      }
    },
    "tagFill": {
      "lightness": 0.33,
      "chromaCap": 0.06
    },
    "seq": {
      "lanes": [
        {
          "lane": "#199e70",
          "cardFill": "#113f2c",
          "cardTop": "#093b31",
          "cardBottom": "#134a34",
          "line": "#4d96a4"
        },
        {
          "lane": "#d95926",
          "cardFill": "#4f2a1d",
          "cardTop": "#4a2725",
          "cardBottom": "#5e301f",
          "line": "#b3719b"
        },
        {
          "lane": "#3987e5",
          "cardFill": "#1f3654",
          "cardTop": "#20334e",
          "cardBottom": "#233f64",
          "line": "#6b8ac3"
        },
        {
          "lane": "#d55181",
          "cardFill": "#4e2734",
          "cardTop": "#472637",
          "cardBottom": "#5d2c3d",
          "line": "#a576af"
        },
        {
          "lane": "#9085e9",
          "cardFill": "#333053",
          "cardTop": "#2f2e4d",
          "cardBottom": "#3d3963",
          "line": "#878cc5"
        }
      ],
      "noteFill": "#443e37",
      "noteStroke": "#9f814e"
    },
    "roleTexture": {
      "ink": "#757983",
      "opacity": 0
    }
  },
  "midnight": {
    "canvas": "#000000",
    "node": "#10121b",
    "nodeForeground": "#f0f1f6",
    "nodeBorder": "#676b7a",
    "edge": "#828593",
    "primary": "#8f81ff",
    "accent": "#1ad1d1",
    "destructive": "#f4514f",
    "destructiveForeground": "#180807",
    "mutedForeground": "#a1a4b0",
    "foreground": "#f0f1f6",
    "secondary": "#1a1c26",
    "secondaryForeground": "#eaebef",
    "border": "#262832",
    "edgeDrift": "#8487da",
    "criticalCap": "#8f81ff",
    "nodeMeta": "#b6bac8",
    "canvasGrid": "#14161d",
    "nodeRoles": {
      "person": {
        "fill": "#2c2047",
        "border": "#9f85e5"
      },
      "internal": {
        "fill": "#0d2944",
        "border": "#579adc"
      },
      "external": {
        "fill": "#14171d",
        "border": "#676b7a"
      },
      "database": {
        "fill": "#002e2f",
        "border": "#12a7a7"
      },
      "queue": {
        "fill": "#112f19",
        "border": "#60a871"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#112f19",
        "border": "#60a871"
      },
      "end": {
        "fill": "#3a1c2e",
        "border": "#d075ab"
      },
      "step": {
        "fill": "#0d2944",
        "border": "#579adc"
      },
      "decision": {
        "fill": "#342501",
        "border": "#bc9041"
      },
      "io": {
        "fill": "#002e2f",
        "border": "#12a7a7"
      },
      "call": {
        "fill": "#2c2047",
        "border": "#9f85e5"
      }
    },
    "tagFill": {
      "lightness": 0.275,
      "chromaCap": 0.06
    },
    "seq": {
      "lanes": [
        {
          "lane": "#199e70",
          "cardFill": "#00311f",
          "cardTop": "#0f260e",
          "cardBottom": "#013d28",
          "line": "#4693a3"
        },
        {
          "lane": "#d95926",
          "cardFill": "#401c0f",
          "cardTop": "#35150d",
          "cardBottom": "#512312",
          "line": "#b26c96"
        },
        {
          "lane": "#3987e5",
          "cardFill": "#112844",
          "cardTop": "#141e38",
          "cardBottom": "#153255",
          "line": "#6885c2"
        },
        {
          "lane": "#d55181",
          "cardFill": "#3f1a26",
          "cardTop": "#34141e",
          "cardBottom": "#4f2030",
          "line": "#a471ab"
        },
        {
          "lane": "#9085e9",
          "cardFill": "#262243",
          "cardTop": "#221a36",
          "cardBottom": "#312d55",
          "line": "#8588c4"
        }
      ],
      "noteFill": "#2c2622",
      "noteStroke": "#927444"
    },
    "roleTexture": {
      "ink": "#676b7a",
      "opacity": 0
    }
  },
  "contrast": {
    "canvas": "#000000",
    "node": "#070707",
    "nodeForeground": "#ffffff",
    "nodeBorder": "#cdd0df",
    "edge": "#babdcb",
    "primary": "#baafff",
    "accent": "#53f2f2",
    "destructive": "#ff706a",
    "destructiveForeground": "#180807",
    "mutedForeground": "#d7d7d7",
    "foreground": "#ffffff",
    "secondary": "#1b1b1b",
    "secondaryForeground": "#ffffff",
    "border": "#a2a4ab",
    "edgeDrift": "#b3b8ff",
    "criticalCap": "#baafff",
    "nodeMeta": "#dcdee5",
    "canvasGrid": "#2e2e2e",
    "nodeRoles": {
      "person": {
        "fill": "#190f2e",
        "border": "#d4bbff"
      },
      "internal": {
        "fill": "#03172c",
        "border": "#90d4ff"
      },
      "external": {
        "fill": "#090b0f",
        "border": "#cdd0df"
      },
      "database": {
        "fill": "#001c1d",
        "border": "#70ebeb"
      },
      "queue": {
        "fill": "#021c09",
        "border": "#9fe9ae"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#021c09",
        "border": "#9fe9ae"
      },
      "end": {
        "fill": "#250b1b",
        "border": "#f9b6db"
      },
      "step": {
        "fill": "#03172c",
        "border": "#90d4ff"
      },
      "decision": {
        "fill": "#1f1400",
        "border": "#facc7e"
      },
      "io": {
        "fill": "#001c1d",
        "border": "#70ebeb"
      },
      "call": {
        "fill": "#190f2e",
        "border": "#d4bbff"
      }
    },
    "tagFill": {
      "lightness": 0.2,
      "chromaCap": 0.06
    },
    "seq": {
      "lanes": [
        {
          "lane": "#199e70",
          "cardFill": "#001e0e",
          "cardTop": "#091804",
          "cardBottom": "#012b18",
          "line": "#5facbd"
        },
        {
          "lane": "#d95926",
          "cardFill": "#2b0901",
          "cardTop": "#240703",
          "cardBottom": "#3d1103",
          "line": "#cd84af"
        },
        {
          "lane": "#3987e5",
          "cardFill": "#021630",
          "cardTop": "#081029",
          "cardBottom": "#052243",
          "line": "#809edc"
        },
        {
          "lane": "#d55181",
          "cardFill": "#2a0714",
          "cardTop": "#230610",
          "cardBottom": "#3c0e1f",
          "line": "#be89c5"
        },
        {
          "lane": "#9085e9",
          "cardFill": "#15102f",
          "cardTop": "#140c26",
          "cardBottom": "#221c42",
          "line": "#9da1de"
        }
      ],
      "noteFill": "#261f13",
      "noteStroke": "#dfbe8a"
    },
    "roleTexture": {
      "ink": "#cdd0df",
      "opacity": 0
    }
  },
  "blueprint": {
    "canvas": "#011d37",
    "node": "#04213c",
    "nodeForeground": "#eff6fd",
    "nodeBorder": "#6c839b",
    "edge": "#7e95ad",
    "primary": "#9c92ff",
    "accent": "#4ddcdc",
    "destructive": "#fc5855",
    "destructiveForeground": "#180807",
    "mutedForeground": "#a9b9ca",
    "foreground": "#eff6fd",
    "secondary": "#223f5c",
    "secondaryForeground": "#e9eff6",
    "border": "#2d4a68",
    "edgeDrift": "#8298e8",
    "criticalCap": "#9c92ff",
    "nodeMeta": "#b2bfce",
    "canvasGrid": "#324f6e",
    "nodeRoles": {
      "person": {
        "fill": "#3c305c",
        "border": "#a98cf4"
      },
      "internal": {
        "fill": "#1b3a58",
        "border": "#5aa3ec"
      },
      "external": {
        "fill": "#06243f",
        "border": "#6c839b"
      },
      "database": {
        "fill": "#004040",
        "border": "#00b2b2"
      },
      "queue": {
        "fill": "#1f4127",
        "border": "#63b376"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#1f4127",
        "border": "#63b376"
      },
      "end": {
        "fill": "#4e2b3f",
        "border": "#de7bb5"
      },
      "step": {
        "fill": "#1b3a58",
        "border": "#5aa3ec"
      },
      "decision": {
        "fill": "#46350d",
        "border": "#c9983f"
      },
      "io": {
        "fill": "#004040",
        "border": "#00b2b2"
      },
      "call": {
        "fill": "#3c305c",
        "border": "#a98cf4"
      }
    },
    "tagFill": {
      "lightness": 0.33,
      "chromaCap": 0.06
    },
    "seq": {
      "lanes": [
        {
          "lane": "#199e70",
          "cardFill": "#113f2c",
          "cardTop": "#023d30",
          "cardBottom": "#134a34",
          "line": "#399ca3"
        },
        {
          "lane": "#d95926",
          "cardFill": "#4f2a1d",
          "cardTop": "#4e2625",
          "cardBottom": "#5e301f",
          "line": "#b570aa"
        },
        {
          "lane": "#3987e5",
          "cardFill": "#1f3654",
          "cardTop": "#1c3452",
          "cardBottom": "#233f64",
          "line": "#598fcc"
        },
        {
          "lane": "#d55181",
          "cardFill": "#4e2734",
          "cardTop": "#492539",
          "cardBottom": "#5d2c3d",
          "line": "#a277bf"
        },
        {
          "lane": "#9085e9",
          "cardFill": "#333053",
          "cardTop": "#2e2f51",
          "cardBottom": "#3d3963",
          "line": "#7c90d2"
        }
      ],
      "noteFill": "#384753",
      "noteStroke": "#9c8b66"
    },
    "roleTexture": {
      "ink": "#6c839b",
      "opacity": 0
    }
  },
  "eink": {
    "canvas": "#ededed",
    "node": "#fafafa",
    "nodeForeground": "#161616",
    "nodeBorder": "#808080",
    "edge": "#696969",
    "primary": "#4d4d4d",
    "accent": "#717171",
    "destructive": "#424242",
    "destructiveForeground": "#fafafa",
    "mutedForeground": "#585858",
    "foreground": "#161616",
    "secondary": "#e6e6e6",
    "secondaryForeground": "#292929",
    "border": "#d4d4d4",
    "edgeDrift": "#585858",
    "criticalCap": "#4d4d4d",
    "nodeMeta": "#3c3c3c",
    "canvasGrid": "#d1d1d1",
    "nodeRoles": {
      "person": {
        "fill": "#dfdfdf",
        "border": "#636363"
      },
      "internal": {
        "fill": "#d7d7d7",
        "border": "#525252"
      },
      "external": {
        "fill": "#f0f0f0",
        "border": "#868686"
      },
      "database": {
        "fill": "#cfcfcf",
        "border": "#424242"
      },
      "queue": {
        "fill": "#e8e8e8",
        "border": "#747474"
      }
    },
    "flowShapes": {
      "start": {
        "fill": "#e8e8e8",
        "border": "#747474"
      },
      "end": {
        "fill": "#bfbfbf",
        "border": "#242424"
      },
      "step": {
        "fill": "#d7d7d7",
        "border": "#525252"
      },
      "decision": {
        "fill": "#c7c7c7",
        "border": "#333333"
      },
      "io": {
        "fill": "#cfcfcf",
        "border": "#424242"
      },
      "call": {
        "fill": "#dfdfdf",
        "border": "#636363"
      }
    },
    "tagFill": {
      "lightness": 0.93,
      "chromaCap": 0.055
    },
    "seq": {
      "lanes": [
        {
          "lane": "#292929",
          "cardFill": "#e8e8e8",
          "cardTop": "#e9e9e9",
          "cardBottom": "#cfcfcf",
          "line": "#444444"
        },
        {
          "lane": "#424242",
          "cardFill": "#e8e8e8",
          "cardTop": "#e9e9e9",
          "cardBottom": "#d2d2d2",
          "line": "#535353"
        },
        {
          "lane": "#5d5d5d",
          "cardFill": "#e8e8e8",
          "cardTop": "#e9e9e9",
          "cardBottom": "#d6d6d6",
          "line": "#626262"
        },
        {
          "lane": "#7a7a7a",
          "cardFill": "#e8e8e8",
          "cardTop": "#e9e9e9",
          "cardBottom": "#dadada",
          "line": "#727272"
        },
        {
          "lane": "#989898",
          "cardFill": "#e8e8e8",
          "cardTop": "#e9e9e9",
          "cardBottom": "#dedede",
          "line": "#828282"
        }
      ],
      "noteFill": "#e9e9e9",
      "noteStroke": "#a8a8a8"
    },
    "roleTexture": {
      "ink": "#4d4d4d",
      "opacity": 0.14
    }
  }
} as const;

/**
 * One theme's palette, for a caller holding a name it has already validated
 * against `THEMES`. Unknown names cannot be constructed through `Theme`, so
 * there is no fallback here to disagree with the route's own default.
 */
export function exportPaletteFor(theme: Theme): ExportTheme {
  return EXPORT_PALETTES[theme];
}
