#!/usr/bin/env node
/**
 * Skill check — the committed `skills/alab/SKILL.md` must be exactly what the
 * generator produces, and must be loadable as a skill.
 *
 * THE FAILURE THIS PREVENTS is silent and slow. The skill is a second copy of
 * the grammar, handed to agents that never call the MCP server — so nothing
 * exercises it. The server's copy is wrong for about one tool call before
 * someone notices; the skill's copy is wrong until it has produced a stack of
 * plausible, invalid `.alab` files in somebody's repo. A generated file that
 * nobody regenerates is exactly as stale as a hand-written one, so the check
 * is that the committed bytes equal the generated bytes.
 *
 * It imports `buildSkill` rather than shelling out to the generator, so
 * running the check can never be the thing that makes the check pass.
 *
 * Run with: pnpm check:skill   (regenerate with pnpm build:skill)
 */

import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..");

// Importing the generator first also installs its `registerHooks` resolver,
// which is what lets the next import reach a .ts module by `@/` path.
const { buildSkill, SKILL_PATH } = await import(
  pathToFileURL(path.join(ROOT, "scripts/build-skill.mjs")).href
);
const { SYNTAX_SECTION_IDS, syntaxSection } = await import(
  pathToFileURL(path.join(ROOT, "src/features/mcp/content/syntax-sections.ts"))
    .href
);
const {
  KINDS_WITHOUT_SYNTAX_SECTIONS,
  KINDS_WITH_SYNTAX_SECTIONS,
  SKILL_DESTINATION,
  SKILL_INSTALL,
  SKILL_INSTALL_ALTERNATIVE,
  SKILL_NAME,
  SKILL_REPO,
  SKILL_SOURCE_DIR,
} = await import(
  pathToFileURL(path.join(ROOT, "src/features/mcp/catalog.ts")).href
);
const { EXAMPLE_NOTATION_LABEL } = await import(
  pathToFileURL(path.join(ROOT, "src/features/playground/lib/kind-copy.ts"))
    .href
);

let assertions = 0;
let failures = 0;
function check(label, run) {
  assertions += 1;
  try {
    run();
    console.log(`  ✓ ${label}`);
  } catch (error) {
    failures += 1;
    console.error(`  ✗ ${label}`);
    console.error(`    ${error instanceof Error ? error.message : error}`);
  }
}

const target = path.join(ROOT, SKILL_PATH);
const onDisk = existsSync(target) ? readFileSync(target, "utf8") : null;
const generated = buildSkill();

/* ---- 1. committed == generated ------------------------------------------- */

check("the skill is committed", () => {
  assert.ok(onDisk !== null, `${SKILL_PATH} does not exist — pnpm build:skill`);
});

check("the committed skill is byte-identical to the generated one", () => {
  assert.equal(
    onDisk,
    generated,
    `${SKILL_PATH} is stale or hand-edited. Run: pnpm build:skill`,
  );
});

/* ---- 2. it is a loadable skill ------------------------------------------- */

check("frontmatter declares a name and a description", () => {
  const match = generated.match(/^---\n([\s\S]*?)\n---\n/);
  assert.ok(match, "no YAML frontmatter block");
  assert.match(match[1], /^name: [a-z0-9-]+$/m, "name must be a slug");
  assert.match(match[1], /^description: \S/m, "description must be non-empty");
});

check("the description says WHEN to use it, not just what it is", () => {
  // An agent reads only this line before deciding whether to open the skill.
  // "The .alab format" gets it loaded when nobody needed it and skipped when
  // they did, so the description has to name the trigger.
  const description = generated.match(/^description: (.+)$/m)[1];
  assert.match(
    description,
    /\.alab/,
    "the description must name the file extension it triggers on",
  );
  assert.match(
    description,
    /\bUse\b|\bwhenever\b|\bwhen\b/,
    "the description must say when to use it",
  );
});

/* ---- 3. it does not hardcode anything that can go stale ------------------ */

check("no hand-typed site origin — it comes from lib/origin.ts", () => {
  // That module exists because a hardcoded origin went stale when the
  // subdomain changed and /mcp advertised a dead endpoint for a day. A second
  // copy buried in a generated file is how that recurs unwatched.
  const source = readFileSync(
    path.join(ROOT, "scripts/build-skill.mjs"),
    "utf8",
  );
  assert.match(source, /DEFAULT_PUBLIC_ORIGIN/);
  const literals = source.match(/https:\/\/(?!\S*\$\{)[a-z0-9.-]+/gi) ?? [];
  assert.deepEqual(
    literals.filter((url) => !url.includes("modelcontextprotocol.io")),
    [],
    `hardcoded URL(s) in the generator: ${literals.join(", ")}`,
  );
});

/* ---- 4. the grammar actually made it in ---------------------------------- */

check("every syntax section reached the skill", () => {
  // The whole point is that this is the complete grammar. A generator that
  // silently dropped a section would produce a confident, incomplete skill.
  for (const id of SYNTAX_SECTION_IDS) {
    const { title } = syntaxSection(id);
    assert.ok(
      generated.includes(`## ${title}`),
      `section "${title}" (${id}) is missing from the skill`,
    );
  }
});

check("the contents links resolve to real headings", () => {
  const toc = [...generated.matchAll(/^- \[.+?\]\(#(.+?)\)$/gm)].map(
    (m) => m[1],
  );
  assert.ok(toc.length > 0, "no contents list");
  const headings = [...generated.matchAll(/^## (.+)$/gm)].map((m) =>
    m[1]
      .toLowerCase()
      .replace(/[^\w\s-]/g, "")
      .trim()
      .replace(/\s+/g, "-"),
  );
  for (const anchor of toc) {
    assert.ok(
      headings.includes(anchor),
      `contents links to #${anchor}, which is not a heading`,
    );
  }
});

check("it tells the reader what a skill alone cannot do", () => {
  // The honest boundary: a file in your project carries the grammar, it does
  // not carry the parser. Someone who thinks otherwise will trust an invalid
  // file because "the skill said so".
  assert.match(generated, /cannot give you is the parser/i);
  assert.match(generated, /validate_model|validator/);
});

/* ---- 5. the documented command installs THIS file ------------------------ */

/*
 * The page tells people to run a command. If that command names a directory
 * the repo does not have, it fails with "could not find subdirectory" and the
 * reader concludes the project is broken — and nothing else in the build would
 * notice, because the string is just prose to everything except the person
 * pasting it.
 */

check("the install command points at the directory the skill lives in", () => {
  assert.equal(
    `${SKILL_SOURCE_DIR}/SKILL.md`,
    SKILL_PATH,
    `the command copies ${SKILL_SOURCE_DIR} but the skill is at ${SKILL_PATH}`,
  );
  assert.ok(
    existsSync(path.join(ROOT, SKILL_SOURCE_DIR)),
    `${SKILL_SOURCE_DIR} does not exist in the repo`,
  );
});

check("both commands run today, with no publish step in the way", () => {
  /* TWO COMMANDS, and the page is only honest if both work. The recommended
     one runs somebody else's published CLI (`skills`, from vercel-labs) which
     resolves a skill out of a public git repo; the alternative copies the
     directory. Neither waits on a release of ours, which is the property that
     matters — the module's own comment records that the ORIGINAL argument for
     degit ("npx <name> needs something published to npm") was about a package
     of ours and outlived its own premise. */
  assert.match(
    SKILL_INSTALL,
    /^npx skills add /,
    "the recommended command is no longer the skills CLI",
  );
  assert.ok(
    SKILL_INSTALL.includes(SKILL_REPO),
    `the command does not name ${SKILL_REPO}`,
  );
  assert.ok(
    SKILL_INSTALL.includes(`--skill ${SKILL_NAME}`),
    "the command does not cherry-pick this skill, so a reader with one repo " +
      "full of skills is offered all of them",
  );

  assert.match(SKILL_INSTALL_ALTERNATIVE, /^npx degit /);
  assert.ok(
    SKILL_INSTALL_ALTERNATIVE.includes(`${SKILL_REPO}/${SKILL_SOURCE_DIR}`),
    `the alternative does not name ${SKILL_REPO}/${SKILL_SOURCE_DIR}`,
  );
});

check("the skill's name is its directory, as the spec requires", () => {
  /* The open Agent Skills spec requires `name` to equal the parent directory,
     and both install commands depend on it separately: the CLI cherry-picks by
     that name, and degit's destination path ends in it. Three things that must
     agree, in one assertion, because they are one fact. */
  assert.equal(
    SKILL_SOURCE_DIR,
    `skills/${SKILL_NAME}`,
    "the skill's directory is not named after the skill",
  );
  assert.match(
    generated,
    new RegExp(`^name: ${SKILL_NAME}$`, "m"),
    "the frontmatter name does not match the directory the CLI resolves it by",
  );
});

check("the alternative writes where the page says it does", () => {
  // degit copies the CONTENTS of the source dir into the destination, so the
  // file lands at <dest>/SKILL.md — the page must not promise a different path.
  const destinationDir = SKILL_INSTALL_ALTERNATIVE.trim().split(/\s+/).at(-1);
  assert.equal(
    `${destinationDir}/SKILL.md`,
    SKILL_DESTINATION,
    `the command writes into ${destinationDir} but the page says ${SKILL_DESTINATION}`,
  );
});

check("the skill does not claim notations it has no section for", () => {
  /* IT CLAIMED TO BE "the complete .alab grammar" while four of the nine
     notations had no section in it. That is the same failure the MCP handshake
     was fixed for — an agent told to read the grammar before writing a
     flowchart found no mention of flowcharts and could reasonably conclude the
     format has none — and the skill did not get the fix at the time. Both ends
     are derived from the section list, so neither can drift again. */
  assert.doesNotMatch(
    generated,
    /complete `?\.alab`? grammar/i,
    "the skill calls itself complete; it teaches " +
      `${KINDS_WITH_SYNTAX_SECTIONS.length} of ` +
      `${KINDS_WITH_SYNTAX_SECTIONS.length + KINDS_WITHOUT_SYNTAX_SECTIONS.length}`,
  );
  for (const kind of KINDS_WITHOUT_SYNTAX_SECTIONS) {
    assert.ok(
      generated.includes(EXAMPLE_NOTATION_LABEL[kind]),
      `the skill never mentions the ${EXAMPLE_NOTATION_LABEL[kind]}, so an ` +
        "agent cannot learn that arch-lab draws one",
    );
  }
  assert.match(
    generated,
    /get_example_model/,
    "the four notations it does not teach are named with nowhere to go",
  );
});

check("an agent reading llms.txt is told the skill exists", () => {
  /* THE GAP THIS EXISTS FOR. The skill was named on exactly one page — `/mcp`,
     which a reader reaches by having already decided they want the server. An
     agent crawling `llms.txt`, which is the audience that file is FOR, was told
     only about the connector and never about the file that needs no connector.
     Nothing failed; the cheaper option was simply undiscoverable. */
  for (const rel of [
    "src/app/llms.txt/route.ts",
    "src/app/llms-full.txt/route.ts",
  ]) {
    const source = readFileSync(path.join(ROOT, rel), "utf8");
    assert.match(
      source,
      /SKILL_INSTALL/,
      `${rel} names the MCP endpoint and never the skill, so an agent reading ` +
        "it cannot learn there is a way to get the grammar without connecting",
    );
    assert.match(
      source,
      /SKILL_INSTALL_ALTERNATIVE/,
      `${rel} offers only one of the two install routes`,
    );
  }
});

check("the /mcp page offers both commands", () => {
  const page = readFileSync(
    path.join(ROOT, "src/features/mcp/components/mcp-guide.tsx"),
    "utf8",
  );
  assert.match(page, /snippet=\{SKILL_INSTALL\}/);
  assert.match(
    page,
    /snippet=\{SKILL_INSTALL_ALTERNATIVE\}/,
    "the page recommends a CLI with telemetry on by default and gives the " +
      "reader no way around it",
  );
});

/* ----------------------------------------------------------------------- */

if (failures > 0) {
  console.error(`\n${failures} of ${assertions} assertion(s) FAILED`);
  process.exit(1);
}
console.log(`\nAll ${assertions} skill assertions passed.`);
