#!/usr/bin/env node
/**
 * Skill check — the committed `skills/alab/SKILL.md` must be exactly what the
 * generator produces, and must be loadable as a skill.
 *
 * THE FAILURE THIS PREVENTS is silent and slow. The skill is a second copy of
 * the grammar, handed to agents that never call the MCP server — so nothing
 * exercises it. The server's copy is wrong for about one tool call before
 * someone notices; the skill's copy is wrong until it has produced a stack of
 * plausible, invalid `.alab` files in somebody's repo. A generated file that
 * nobody regenerates is exactly as stale as a hand-written one, so the check
 * is that the committed bytes equal the generated bytes.
 *
 * It imports `buildSkill` rather than shelling out to the generator, so
 * running the check can never be the thing that makes the check pass.
 *
 * Run with: pnpm check:skill   (regenerate with pnpm build:skill)
 */

import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..");

// Importing the generator first also installs its `registerHooks` resolver,
// which is what lets the next import reach a .ts module by `@/` path.
const { buildSkill, SKILL_PATH } = await import(
  pathToFileURL(path.join(ROOT, "scripts/build-skill.mjs")).href
);
const { SYNTAX_SECTION_IDS, syntaxSection } = await import(
  pathToFileURL(path.join(ROOT, "src/features/mcp/content/syntax-sections.ts"))
    .href
);
const { SKILL_INSTALL, SKILL_REPO, SKILL_SOURCE_DIR, SKILL_DESTINATION } =
  await import(
    pathToFileURL(path.join(ROOT, "src/features/mcp/catalog.ts")).href
  );

let assertions = 0;
let failures = 0;
function check(label, run) {
  assertions += 1;
  try {
    run();
    console.log(`  ✓ ${label}`);
  } catch (error) {
    failures += 1;
    console.error(`  ✗ ${label}`);
    console.error(`    ${error instanceof Error ? error.message : error}`);
  }
}

const target = path.join(ROOT, SKILL_PATH);
const onDisk = existsSync(target) ? readFileSync(target, "utf8") : null;
const generated = buildSkill();

/* ---- 1. committed == generated ------------------------------------------- */

check("the skill is committed", () => {
  assert.ok(onDisk !== null, `${SKILL_PATH} does not exist — pnpm build:skill`);
});

check("the committed skill is byte-identical to the generated one", () => {
  assert.equal(
    onDisk,
    generated,
    `${SKILL_PATH} is stale or hand-edited. Run: pnpm build:skill`,
  );
});

/* ---- 2. it is a loadable skill ------------------------------------------- */

check("frontmatter declares a name and a description", () => {
  const match = generated.match(/^---\n([\s\S]*?)\n---\n/);
  assert.ok(match, "no YAML frontmatter block");
  assert.match(match[1], /^name: [a-z0-9-]+$/m, "name must be a slug");
  assert.match(match[1], /^description: \S/m, "description must be non-empty");
});

check("the description says WHEN to use it, not just what it is", () => {
  // An agent reads only this line before deciding whether to open the skill.
  // "The .alab format" gets it loaded when nobody needed it and skipped when
  // they did, so the description has to name the trigger.
  const description = generated.match(/^description: (.+)$/m)[1];
  assert.match(
    description,
    /\.alab/,
    "the description must name the file extension it triggers on",
  );
  assert.match(
    description,
    /\bUse\b|\bwhenever\b|\bwhen\b/,
    "the description must say when to use it",
  );
});

/* ---- 3. it does not hardcode anything that can go stale ------------------ */

check("no hand-typed site origin — it comes from lib/origin.ts", () => {
  // That module exists because a hardcoded origin went stale when the
  // subdomain changed and /mcp advertised a dead endpoint for a day. A second
  // copy buried in a generated file is how that recurs unwatched.
  const source = readFileSync(
    path.join(ROOT, "scripts/build-skill.mjs"),
    "utf8",
  );
  assert.match(source, /DEFAULT_PUBLIC_ORIGIN/);
  const literals = source.match(/https:\/\/(?!\S*\$\{)[a-z0-9.-]+/gi) ?? [];
  assert.deepEqual(
    literals.filter((url) => !url.includes("modelcontextprotocol.io")),
    [],
    `hardcoded URL(s) in the generator: ${literals.join(", ")}`,
  );
});

/* ---- 4. the grammar actually made it in ---------------------------------- */

check("every syntax section reached the skill", () => {
  // The whole point is that this is the complete grammar. A generator that
  // silently dropped a section would produce a confident, incomplete skill.
  for (const id of SYNTAX_SECTION_IDS) {
    const { title } = syntaxSection(id);
    assert.ok(
      generated.includes(`## ${title}`),
      `section "${title}" (${id}) is missing from the skill`,
    );
  }
});

check("the contents links resolve to real headings", () => {
  const toc = [...generated.matchAll(/^- \[.+?\]\(#(.+?)\)$/gm)].map(
    (m) => m[1],
  );
  assert.ok(toc.length > 0, "no contents list");
  const headings = [...generated.matchAll(/^## (.+)$/gm)].map((m) =>
    m[1]
      .toLowerCase()
      .replace(/[^\w\s-]/g, "")
      .trim()
      .replace(/\s+/g, "-"),
  );
  for (const anchor of toc) {
    assert.ok(
      headings.includes(anchor),
      `contents links to #${anchor}, which is not a heading`,
    );
  }
});

check("it tells the reader what a skill alone cannot do", () => {
  // The honest boundary: a file in your project carries the grammar, it does
  // not carry the parser. Someone who thinks otherwise will trust an invalid
  // file because "the skill said so".
  assert.match(generated, /cannot give you is the parser/i);
  assert.match(generated, /validate_model|validator/);
});

/* ---- 5. the documented command installs THIS file ------------------------ */

/*
 * The page tells people to run a command. If that command names a directory
 * the repo does not have, it fails with "could not find subdirectory" and the
 * reader concludes the project is broken — and nothing else in the build would
 * notice, because the string is just prose to everything except the person
 * pasting it.
 */

check("the install command points at the directory the skill lives in", () => {
  assert.equal(
    `${SKILL_SOURCE_DIR}/SKILL.md`,
    SKILL_PATH,
    `the command copies ${SKILL_SOURCE_DIR} but the skill is at ${SKILL_PATH}`,
  );
  assert.ok(
    existsSync(path.join(ROOT, SKILL_SOURCE_DIR)),
    `${SKILL_SOURCE_DIR} does not exist in the repo`,
  );
});

check("the command is npx-able as written, with no publish step", () => {
  // `npx <name>` would need an npm package, and nothing here is published.
  // degit reads the public GitHub repo directly, so the documented command is
  // one that runs today rather than after a release nobody has scheduled.
  assert.match(SKILL_INSTALL, /^npx degit /);
  assert.ok(
    SKILL_INSTALL.includes(`${SKILL_REPO}/${SKILL_SOURCE_DIR}`),
    `the command does not name ${SKILL_REPO}/${SKILL_SOURCE_DIR}`,
  );
});

check("the destination it advertises is where degit actually writes", () => {
  // degit copies the CONTENTS of the source dir into the destination, so the
  // file lands at <dest>/SKILL.md — the page must not promise a different path.
  const destinationDir = SKILL_INSTALL.trim().split(/\s+/).at(-1);
  assert.equal(
    `${destinationDir}/SKILL.md`,
    SKILL_DESTINATION,
    `the command writes into ${destinationDir} but the page says ${SKILL_DESTINATION}`,
  );
});

/* ----------------------------------------------------------------------- */

if (failures > 0) {
  console.error(`\n${failures} of ${assertions} assertion(s) FAILED`);
  process.exit(1);
}
console.log(`\nAll ${assertions} skill assertions passed.`);
