#!/usr/bin/env node
/**
 * Skill check — the committed `skills/alab/SKILL.md` must be exactly what the
 * generator produces, and must be loadable as a skill.
 *
 * THE FAILURE THIS PREVENTS is silent and slow. The skill is a second copy of
 * the grammar, handed to agents that never call the MCP server — so nothing
 * exercises it. The server's copy is wrong for about one tool call before
 * someone notices; the skill's copy is wrong until it has produced a stack of
 * plausible, invalid `.alab` files in somebody's repo. A generated file that
 * nobody regenerates is exactly as stale as a hand-written one, so the check
 * is that the committed bytes equal the generated bytes.
 *
 * It imports `buildSkill` rather than shelling out to the generator, so
 * running the check can never be the thing that makes the check pass.
 *
 * Run with: pnpm check:skill   (regenerate with pnpm build:skill)
 */

import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..");

// Importing the generator first also installs its `registerHooks` resolver,
// which is what lets the next import reach a .ts module by `@/` path.
const { REFERENCE_DIR, SKILL_PATH, buildSkillFiles } = await import(
  pathToFileURL(path.join(ROOT, "scripts/build-skill.mjs")).href
);
const { SYNTAX_SECTION_IDS, syntaxSection } = await import(
  pathToFileURL(path.join(ROOT, "src/features/mcp/content/syntax-sections.ts"))
    .href
);
const {
  KINDS_WITHOUT_SYNTAX_SECTIONS,
  KINDS_WITH_SYNTAX_SECTIONS,
  SKILL_DESTINATION,
  SKILL_INSTALL,
  SKILL_INSTALL_ALTERNATIVE,
  SKILL_NAME,
  SKILL_REPO,
  SKILL_SOURCE_DIR,
} = await import(
  pathToFileURL(path.join(ROOT, "src/features/mcp/catalog.ts")).href
);
const { EXAMPLE_NOTATION_LABEL } = await import(
  pathToFileURL(path.join(ROOT, "src/features/playground/lib/kind-copy.ts"))
    .href
);

let assertions = 0;
let failures = 0;
function check(label, run) {
  assertions += 1;
  try {
    run();
    console.log(`  ✓ ${label}`);
  } catch (error) {
    failures += 1;
    console.error(`  ✗ ${label}`);
    console.error(`    ${error instanceof Error ? error.message : error}`);
  }
}

const target = path.join(ROOT, SKILL_PATH);
const onDisk = existsSync(target) ? readFileSync(target, "utf8") : null;
const generatedFiles = buildSkillFiles();
const generated = generatedFiles.get("SKILL.md");

/** Every generated file's committed twin, or null where it is missing. */
const committedFiles = new Map(
  [...generatedFiles.keys()].map((relative) => {
    const file = path.join(ROOT, SKILL_SOURCE_DIR, relative);
    return [relative, existsSync(file) ? readFileSync(file, "utf8") : null];
  }),
);

/* ---- 1. committed == generated ------------------------------------------- */

check("the skill is committed", () => {
  assert.ok(onDisk !== null, `${SKILL_PATH} does not exist — pnpm build:skill`);
});

check("every committed file is byte-identical to the generated one", () => {
  for (const [relative, contents] of generatedFiles) {
    assert.equal(
      committedFiles.get(relative),
      contents,
      `${SKILL_SOURCE_DIR}/${relative} is stale or hand-edited. ` +
        "Run: pnpm build:skill",
    );
  }
});

check("no orphan file is left in the skill directory", () => {
  /* BOTH INSTALL ROUTES COPY THE WHOLE DIRECTORY, so a reference file left
     behind by a rename travels to every reader as a grammar nothing links to
     and nothing regenerates — and being generated-looking, it would be trusted.
     The generator removes them; this is what notices if it stops. */
  const dir = path.join(ROOT, SKILL_SOURCE_DIR, REFERENCE_DIR);
  const onDiskNames = existsSync(dir) ? readdirSync(dir) : [];
  for (const name of onDiskNames) {
    assert.ok(
      generatedFiles.has(`${REFERENCE_DIR}/${name}`),
      `${SKILL_SOURCE_DIR}/${REFERENCE_DIR}/${name} is not generated by ` +
        "build-skill.mjs — a rename left it behind",
    );
  }
});

/* ---- 2. it is a loadable skill ------------------------------------------- */

check("frontmatter declares a name and a description", () => {
  const match = generated.match(/^---\n([\s\S]*?)\n---\n/);
  assert.ok(match, "no YAML frontmatter block");
  assert.match(match[1], /^name: [a-z0-9-]+$/m, "name must be a slug");
  assert.match(match[1], /^description: \S/m, "description must be non-empty");
});

check("the description says WHEN to use it, not just what it is", () => {
  // An agent reads only this line before deciding whether to open the skill.
  // "The .alab format" gets it loaded when nobody needed it and skipped when
  // they did, so the description has to name the trigger.
  const description = generated.match(/^description: (.+)$/m)[1];
  assert.match(
    description,
    /\.alab/,
    "the description must name the file extension it triggers on",
  );
  assert.match(
    description,
    /\bUse\b|\bwhenever\b|\bwhen\b/,
    "the description must say when to use it",
  );
});

/* ---- 3. it does not hardcode anything that can go stale ------------------ */

check("no hand-typed site origin — it comes from lib/origin.ts", () => {
  // That module exists because a hardcoded origin went stale when the
  // subdomain changed and /mcp advertised a dead endpoint for a day. A second
  // copy buried in a generated file is how that recurs unwatched.
  const source = readFileSync(
    path.join(ROOT, "scripts/build-skill.mjs"),
    "utf8",
  );
  assert.match(source, /DEFAULT_PUBLIC_ORIGIN/);
  const literals = source.match(/https:\/\/(?!\S*\$\{)[a-z0-9.-]+/gi) ?? [];
  assert.deepEqual(
    literals.filter((url) => !url.includes("modelcontextprotocol.io")),
    [],
    `hardcoded URL(s) in the generator: ${literals.join(", ")}`,
  );
});

/* ---- 4. the grammar actually made it in ---------------------------------- */

check("every syntax section reached exactly one file", () => {
  /* A generator that silently dropped a section would produce a confident,
     incomplete skill — and now that the sections are spread over seven files,
     it could also write one TWICE, which is the same grammar in two places and
     therefore one place that will go quietly wrong. Counted across every file,
     so both failures are caught by one assertion. */
  const all = [...generatedFiles.values()];
  for (const id of SYNTAX_SECTION_IDS) {
    const { title } = syntaxSection(id);
    const homes = all.filter((body) => body.includes(`## ${title}`)).length;
    assert.equal(
      homes,
      1,
      homes === 0
        ? `section "${title}" (${id}) is in no file — it vanished from the skill`
        : `section "${title}" (${id}) is in ${homes} files`,
    );
  }
});

check("SKILL.md stays inside the budget that motivated the split", () => {
  /* THE SPEC'S NUMBERS, and the reason this file is not one file any more. A
     body under ~5,000 tokens and under 500 lines; the whole reference is ~7,700
     tokens and used to be all of it here. Asserted rather than remembered,
     because a section added to the entry file is the easiest way to walk back
     into the shape this replaced.

     Tokens are estimated at four characters each. That is not a tokenizer, and
     it does not need to be: the budget is an order of magnitude away, and a
     check that needed a tokenizer to run would not run. */
  const lines = generated.split("\n").length;
  const tokens = Math.round(generated.length / 4);
  assert.ok(
    lines < 500,
    `SKILL.md is ${lines} lines; the spec asks for under 500`,
  );
  assert.ok(
    tokens < 5000,
    `SKILL.md is ~${tokens} tokens; the spec asks for under 5,000`,
  );
  for (const [relative, body] of generatedFiles) {
    assert.ok(
      Math.round(body.length / 4) < 5000,
      `${relative} is ~${Math.round(body.length / 4)} tokens — a reference ` +
        "file a reader is told to open in full has the same budget",
    );
  }
});

check("no reference file is empty", () => {
  /* THE MUTATION THAT GOT THROUGH. Moving every C4 section back into SKILL.md
     left `reference/c4.md` generated, linked from the routing table, and
     carrying no grammar at all — and the budget assertion above still passed,
     because the entry file was under the cap even holding all of it. A reader
     sent to an empty file concludes the notation is undocumented; the check has
     to notice the file is hollow, not just that it exists. */
  for (const [relative, body] of generatedFiles) {
    if (relative === "SKILL.md") continue;
    assert.match(
      body,
      /^## /m,
      `${relative} contains no section — it is linked from SKILL.md and has ` +
        "nothing in it",
    );
  }
});

check(
  "the entry file routes to every reference, and every link resolves",
  () => {
    /* A list of files is not progressive disclosure. The reader has to be able to
     pick their file WITHOUT opening any of them, so the entry file must link
     all of them and say when each applies — and a link that resolves to
     nothing is worse than no link, because the agent will go looking. */
    const links = [...generated.matchAll(/\]\((reference\/[^)]+)\)/g)].map(
      (match) => match[1],
    );
    assert.ok(links.length > 0, "SKILL.md links to no reference file");
    for (const link of links) {
      assert.ok(
        generatedFiles.has(link),
        `SKILL.md links to ${link}, which is not generated`,
      );
      assert.ok(
        existsSync(path.join(ROOT, SKILL_SOURCE_DIR, link)),
        `SKILL.md links to ${link}, which is not on disk`,
      );
    }
    for (const relative of generatedFiles.keys()) {
      if (relative === "SKILL.md") continue;
      assert.ok(
        links.includes(relative),
        `${relative} is generated but nothing in SKILL.md points at it — a ` +
          "reader has no way to discover it",
      );
    }
  },
);

check("it tells the reader what a skill alone cannot do", () => {
  // The honest boundary: a file in your project carries the grammar, it does
  // not carry the parser. Someone who thinks otherwise will trust an invalid
  // file because "the skill said so".
  assert.match(generated, /cannot give you is the parser/i);
  assert.match(generated, /validate_model|validator/);
});

/* ---- 5. the documented command installs THIS file ------------------------ */

/*
 * The page tells people to run a command. If that command names a directory
 * the repo does not have, it fails with "could not find subdirectory" and the
 * reader concludes the project is broken — and nothing else in the build would
 * notice, because the string is just prose to everything except the person
 * pasting it.
 */

check("the install command points at the directory the skill lives in", () => {
  assert.equal(
    `${SKILL_SOURCE_DIR}/SKILL.md`,
    SKILL_PATH,
    `the command copies ${SKILL_SOURCE_DIR} but the skill is at ${SKILL_PATH}`,
  );
  assert.ok(
    existsSync(path.join(ROOT, SKILL_SOURCE_DIR)),
    `${SKILL_SOURCE_DIR} does not exist in the repo`,
  );
});

check("both commands run today, with no publish step in the way", () => {
  /* TWO COMMANDS, and the page is only honest if both work. The recommended
     one runs somebody else's published CLI (`skills`, from vercel-labs) which
     resolves a skill out of a public git repo; the alternative copies the
     directory. Neither waits on a release of ours, which is the property that
     matters — the module's own comment records that the ORIGINAL argument for
     degit ("npx <name> needs something published to npm") was about a package
     of ours and outlived its own premise. */
  assert.match(
    SKILL_INSTALL,
    /^npx skills add /,
    "the recommended command is no longer the skills CLI",
  );
  assert.ok(
    SKILL_INSTALL.includes(SKILL_REPO),
    `the command does not name ${SKILL_REPO}`,
  );
  assert.ok(
    SKILL_INSTALL.includes(`--skill ${SKILL_NAME}`),
    "the command does not cherry-pick this skill, so a reader with one repo " +
      "full of skills is offered all of them",
  );

  assert.match(SKILL_INSTALL_ALTERNATIVE, /^npx degit /);
  assert.ok(
    SKILL_INSTALL_ALTERNATIVE.includes(`${SKILL_REPO}/${SKILL_SOURCE_DIR}`),
    `the alternative does not name ${SKILL_REPO}/${SKILL_SOURCE_DIR}`,
  );
});

check("the skill's name is its directory, as the spec requires", () => {
  /* The open Agent Skills spec requires `name` to equal the parent directory,
     and both install commands depend on it separately: the CLI cherry-picks by
     that name, and degit's destination path ends in it. Three things that must
     agree, in one assertion, because they are one fact. */
  assert.equal(
    SKILL_SOURCE_DIR,
    `skills/${SKILL_NAME}`,
    "the skill's directory is not named after the skill",
  );
  assert.match(
    generated,
    new RegExp(`^name: ${SKILL_NAME}$`, "m"),
    "the frontmatter name does not match the directory the CLI resolves it by",
  );
});

check("the alternative writes where the page says it does", () => {
  // degit copies the CONTENTS of the source dir into the destination, so the
  // file lands at <dest>/SKILL.md — the page must not promise a different path.
  const destinationDir = SKILL_INSTALL_ALTERNATIVE.trim().split(/\s+/).at(-1);
  assert.equal(
    `${destinationDir}/SKILL.md`,
    SKILL_DESTINATION,
    `the command writes into ${destinationDir} but the page says ${SKILL_DESTINATION}`,
  );
});

check("the skill does not claim notations it has no section for", () => {
  /* IT CLAIMED TO BE "the complete .alab grammar" while four of the nine
     notations had no section in it. That is the same failure the MCP handshake
     was fixed for — an agent told to read the grammar before writing a
     flowchart found no mention of flowcharts and could reasonably conclude the
     format has none — and the skill did not get the fix at the time. Both ends
     are derived from the section list, so neither can drift again. */
  assert.doesNotMatch(
    generated,
    /complete `?\.alab`? grammar/i,
    "the skill calls itself complete; it teaches " +
      `${KINDS_WITH_SYNTAX_SECTIONS.length} of ` +
      `${KINDS_WITH_SYNTAX_SECTIONS.length + KINDS_WITHOUT_SYNTAX_SECTIONS.length}`,
  );
  for (const kind of KINDS_WITHOUT_SYNTAX_SECTIONS) {
    assert.ok(
      generated.includes(EXAMPLE_NOTATION_LABEL[kind]),
      `the skill never mentions the ${EXAMPLE_NOTATION_LABEL[kind]}, so an ` +
        "agent cannot learn that arch-lab draws one",
    );
  }
  assert.match(
    generated,
    /get_example_model/,
    "the four notations it does not teach are named with nowhere to go",
  );
});

check("an agent reading llms.txt is told the skill exists", () => {
  /* THE GAP THIS EXISTS FOR. The skill was named on exactly one page — `/mcp`,
     which a reader reaches by having already decided they want the server. An
     agent crawling `llms.txt`, which is the audience that file is FOR, was told
     only about the connector and never about the file that needs no connector.
     Nothing failed; the cheaper option was simply undiscoverable. */
  for (const rel of [
    "src/app/llms.txt/route.ts",
    "src/app/llms-full.txt/route.ts",
  ]) {
    const source = readFileSync(path.join(ROOT, rel), "utf8");
    assert.match(
      source,
      /SKILL_INSTALL/,
      `${rel} names the MCP endpoint and never the skill, so an agent reading ` +
        "it cannot learn there is a way to get the grammar without connecting",
    );
    assert.match(
      source,
      /SKILL_INSTALL_ALTERNATIVE/,
      `${rel} offers only one of the two install routes`,
    );
  }
});

check("the skill's own page offers both commands", () => {
  /* MOVED FROM `/mcp`, with the route. The skill was a section on the connect
     guide, which documented the cheaper integration only to readers who had
     already chosen the other one; it has a page now, and the assertion
     follows what it is asserting about. The second command is the load-bearing
     half: the skills CLI reports installs to its own telemetry endpoint by
     default, and a page that recommends it with no alternative gives the
     reader no way around that. */
  const page = readFileSync(
    path.join(ROOT, "src/features/mcp/components/skill-guide.tsx"),
    "utf8",
  );
  assert.match(page, /snippet=\{SKILL_INSTALL\}/);
  assert.match(
    page,
    /snippet=\{SKILL_INSTALL_ALTERNATIVE\}/,
    "the page recommends a CLI with telemetry on by default and gives the " +
      "reader no way around it",
  );
});

check("/mcp offers the skill and sends the reader to its page", () => {
  /* THE POINTER IS THE WHOLE REASON THE SPLIT IS SAFE. `/mcp` stopped carrying
     the argument for the skill so the two pages would not compete for one
     canonical — which is only an improvement while the pointer survives. Drop
     the link and the connect guide silently becomes the page that never
     mentions the cheaper option again. */
  const page = readFileSync(
    path.join(ROOT, "src/features/mcp/components/mcp-guide.tsx"),
    "utf8",
  );
  assert.match(
    page,
    /snippet=\{SKILL_INSTALL\}/,
    "/mcp names no install command",
  );
  assert.match(
    page,
    /href="\/skill"/,
    "/mcp shows the skill's command and never links to what it installs",
  );
});

check(
  "the skill is offered where a reader has not chosen an integration",
  () => {
    /* THREE SURFACES, and none of them is `/mcp`: the landing page (where the
     choice is actually made), the FAQ (which feeds this site's only `FAQPage`
     structured data, so an answer there is the one an assistant can quote with
     attribution), and the sitemap (a fragment is not a page a crawler ranks).
     Every one of these was absent while the skill shipped, and none of them
     fails on its own — the skill simply stayed undiscoverable. */
    const home = readFileSync(path.join(ROOT, "src/app/page.tsx"), "utf8");
    assert.match(
      home,
      /snippet=\{SKILL_INSTALL\}/,
      "the landing page offers the MCP command alone, so the skill is reachable " +
        "only by a reader who has already decided to add a server",
    );
    assert.match(
      home,
      /Agent Skill carrying the \.alab grammar/,
      "the home page's JSON-LD featureList names the server and not the skill, " +
        "which tells an assistant reading it that the skill does not exist",
    );

    const faq = readFileSync(
      path.join(ROOT, "src/features/marketing/faq.ts"),
      "utf8",
    );
    assert.match(
      faq,
      /SKILL_INSTALL/,
      "no FAQ answer mentions the skill, so the site's most quotable page has " +
        "nothing to say to somebody who does not want to run a server",
    );

    const sitemap = readFileSync(path.join(ROOT, "src/app/sitemap.ts"), "utf8");
    assert.match(
      sitemap,
      /"\/skill"/,
      "the skill page is not in the sitemap — a page nothing crawls",
    );
  },
);

/* ----------------------------------------------------------------------- */

if (failures > 0) {
  console.error(`\n${failures} of ${assertions} assertion(s) FAILED`);
  process.exit(1);
}
console.log(`\nAll ${assertions} skill assertions passed.`);
